### ISSUE TITLE
[Issue] Executable file is not outputted after auto compilation process is completed when the ``--auto-compile-name`` option is specified

### ISSUE THREAD

**Issue by Arc8ne** [ayecue/greybel-js#185]
Here is the command that I ran as well as the output from greybel-js after attempting to build my Greyscript project using it:
```
greybel --auto-compile-name program --disable-build-folder --auto-compile-purge --create-ingame-mode "local" --create-ingame --installer --auto-compile --ingame-directory "/usr/bin" "./src/program.src" "./build"

Creating installer.
Importing files ingame.
Trying to connect to 127.0.0.1:21200 (attempt: 0)
Imported /program.src successful
Imported /helpers/enum-helpers.src successful
Imported /command.src successful
Imported /helpers/string-helpers.src successful
Imported /command-factory.src successful
Build done in /usr/bin
Delete pre-existing program done!
Renaming failed! Reason: /usr/bin/program not found
Deleted /usr/bin/program.src
Deleted /usr/bin/helpers/enum-helpers.src
Deleted /usr/bin/command.src
Deleted /usr/bin/helpers/string-helpers.src
Deleted /usr/bin/command-factory.src
Deleted /usr/bin/helpers
5 files got imported to /usr/bin!
Build done. Available in C:\Users\Arcane\Dev\Greyscript-Projects\GS-Program\build.
```

When checking my GH computer after the auto-compilation process was completed, I did not find an executable file called ``program`` in my ``/usr/bin`` folder. I was expecting that such a file would be created as a result of the auto-compilation process.

If necessary, I can provide further details regarding this issue, do let me know if that is indeed the case.

**Comment by ayecue** [comment]
Hey,

here a small explanation what `--auto-compile-name` does. So `--auto-compile-name` does [add additional logic to the auto compile script](https://github.com/ayecue/greybel-js/blob/master/src/build/auto-compile-helper.ts#L29-L40). What it does it mainly renaming the built file to whatever you defined. In order to do that it will check if there is already a file existing which has the name of the value given in `--auto-compile-name` since in GreyScript in order to rename a file you're not allowed to have a file already existing the that name.

So anyway in your case you are building `program.src` when executing `build` it'll generate a file called `program` since in GreyScript when you build something it will automatically remove the file extension. But then you also apply the rename logic even though the file is already named `program` so what will happen instead is that the binary gets deleted and there is no file to rename anymore. So pretty much it's an edge case I didn't think about since I thought you only use `--auto-compile-name` if you want to have a different name then it'll create by default which isn't the case here.

Anyway I'll fix it in the future but maybe in the mean time just use `--auto-compile-name` only if it's a different name then the one automatically given when executing a build via GreyScript.

**Comment by Arc8ne** [comment]
I see, that makes sense, I will do that then. Thanks.

**Comment by ayecue** [comment]
Should be fixed by https://github.com/ayecue/greybel-js/pull/186

**Comment by Arc8ne** [comment]
I see, thank you.
